# -*- coding: utf-8 -*-
"""
Module for downloading content from Deezer.

Provides functions to download tracks, albums and playlists using the Deezer API
and the deemix library, with concurrency management and resource limits.
"""

import os
import asyncio
import logging
import shutil
import uuid
import requests
import time
from typing import Union, List, Dict, Any, Optional, Callable, Awaitable

from deezer import Deezer
from deemix import generateDownloadObject
from deemix.downloader import Downloader

from src.config import DOWNLOAD_PATH, MAX_CONCURRENT_DOWNLOADS_PER_USER


class TrackPreviewUnavailableError(Exception):
    """Exception raised when a track has no preview available on Deezer."""
    pass


class LogListener:
    """
    Class to capture and log messages generated by deemix.
    """
    
    def send(self, key: str, value: Any = None) -> None:
        """
        Processes and logs a deemix log message.
        
        Args:
            key: Message or event identifier
            value: Additional value or information associated with the event
        """
        logging.debug(f"[DEEMIX] {key}: {value}")


async def download_track(
    url: str, 
    dz: Deezer, 
    settings: Dict[str, Any], 
    listener: LogListener, 
    user_id: Optional[int] = None
) -> Union[str, List[str]]:
    """
    Downloads a track, album or playlist from Deezer with concurrency management.
    
    Args:
        url: Deezer URL to download (track, album or playlist)
        dz: Authenticated Deezer class instance
        settings: Dictionary with download configuration
        listener: LogListener instance to receive progress events
        user_id: Optional user ID for resource management and limits
        
    Returns:
        Path to downloaded file or list of paths for albums/playlists
        
    Raises:
        Exception: If an error occurs during download or processing
    """
    # Import here to avoid circular imports
    from src.core.services import UserSession
    from src.core.services.queue_service import QueueManager
    
    # Log download start with timestamp
    start_time = time.time()
    logging.info(f"[DOWNLOADER] Starting download of URL: {url} for user: {user_id}, timestamp: {start_time}")
    
    # If user_id is provided, use queue manager to control concurrency
    if user_id:
        # Get queue manager
        queue_manager = QueueManager.get_instance()
        
        # Get user session for statistics
        session = UserSession.get_session(user_id)
        session.update_activity()
        
        try:
            # Increment active downloads counter
            session.active_downloads += 1
            logging.info(f"[DOWNLOADER] User {user_id} now has {session.active_downloads} active downloads")
            
            # Execute download in background using queues
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None, 
                lambda: sync_download_track(url, dz, settings, listener, user_id)
            )
            logging.info(f"[DOWNLOADER] Download completed for user: {user_id}, time: {time.time() - start_time:.2f}s")
            return result
        finally:
            # Decrement counter on completion
            session.active_downloads -= 1
            logging.info(f"[DOWNLOADER] User {user_id} now has {session.active_downloads} active downloads")
    else:
        # Original behavior for compatibility with legacy code
        logging.info("[DOWNLOADER] Using legacy method without user_id")
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(None, sync_download_track, url, dz, settings, listener)
        logging.info(f"[DOWNLOADER] Legacy download completed, time: {time.time() - start_time:.2f}s")
        return result


def sync_download_track(
    url: str, 
    dz: Deezer, 
    settings: Dict[str, Any], 
    listener: LogListener, 
    user_id: Optional[int] = None
) -> Union[str, List[str]]:
    """
    Synchronous version of the function to download Deezer content.
    
    This function performs the download synchronously and is executed
    in an executor by the async download_track function.
    
    Args:
        url: Deezer URL to download
        dz: Authenticated Deezer class instance
        settings: Dictionary with download configuration
        listener: LogListener instance to receive progress events
        user_id: Optional user ID for file identification
        
    Returns:
        Path to downloaded file or list of paths for albums/playlists
        
    Raises:
        Exception: If an error occurs during download or processing
    """
    # Ensure base download directory exists
    os.makedirs(DOWNLOAD_PATH, exist_ok=True)
    
    # Create unique temporary directory to avoid conflicts
    # If user_id exists, include it in the path to separate by user
    folder_name = f"temp_{uuid.uuid4().hex}"
    if user_id:
        folder_name = f"user_{user_id}_{folder_name}"
    
    temp_dir = os.path.join(DOWNLOAD_PATH, folder_name)
    os.makedirs(temp_dir, exist_ok=True)
    
    # Save temporary settings for this download
    temp_settings = settings.copy()
    temp_settings["downloadLocation"] = temp_dir
    
    try:
        # Log download start
        logging.info(f"Starting download: {url}" + (f" for user {user_id}" if user_id else ""))
        logging.info("Content type: track")
        
        # Generate download object with desired quality configuration
        bitrate = settings["maxBitrate"]
        plugins = {}  # No additional plugins
        download_obj = generateDownloadObject(dz, url, bitrate, plugins, listener)
        
        # Verify if object is valid
        if not download_obj:
            raise Exception("This song was not found on Deezer")
        
        # Extract information from download object for logging
        obj_info = "Object to download"
        try:
            if hasattr(download_obj, 'title'):
                obj_info += f": {download_obj.title}"
            if hasattr(download_obj, 'artist') and hasattr(download_obj.artist, 'name'):
                obj_info += f" - {download_obj.artist.name}"
        except Exception:
            # Ignore errors when extracting info for logging
            pass
        logging.info(obj_info)

        # Start download using deemix downloader
        downloader = Downloader(dz, download_obj, temp_settings, listener)
        
        # Capture specific errors during download
        try:
            # Log download object info for diagnosis
            track_info = None
            try:
                # Try to get ID from URL for diagnosis
                track_id = url.split("/")[-1]
                if track_id.isdigit():
                    track_info = dz.api.get_track(track_id)
                    if track_info and track_info.get('title'):
                        logging.info(f"Downloading: {track_info.get('title')} - {track_info.get('artist', {}).get('name', 'Unknown')}")
            except Exception:
                pass  # Ignore errors getting info for diagnosis

            downloader.start()
        except IndexError as e:
            error_str = str(e)
            # Capture specific MEDIA-related error
            if 'list index out of range' in error_str:
                track_title = "unknown song"
                if track_info and track_info.get('title'):
                    track_title = f"{track_info.get('title')} - {track_info.get('artist', {}).get('name', 'Unknown')}"
                
                logging.error(f"{track_title} list index out of range")
                raise TrackPreviewUnavailableError(f"Song '{track_title}' is not available on Deezer")
            else:
                raise  # Re-raise other index errors
        except Exception as e:
            error_msg = str(e).lower()
            if "403" in error_msg or "forbidden" in error_msg:
                raise Exception("This song is not available in your region")
            elif "404" in error_msg or "not found" in error_msg:
                raise Exception("This song is no longer available on Deezer")
            elif "copyright" in error_msg or "rights" in error_msg:
                raise Exception("This song has copyright restrictions")
            elif "timeout" in error_msg or "timed out" in error_msg:
                raise Exception("Connection issues. Try again")
            elif "key error" in error_msg or "missing" in error_msg:
                raise Exception("Incomplete information for this song")
            else:
                raise  # Re-raise original exception for other cases
        
        # Search for downloaded audio file in temporary directory
        audio_files = []
        for root, _, files in os.walk(temp_dir):
            for file in files:
                if file.endswith(('.mp3', '.flac', '.m4a')):
                    file_path = os.path.join(root, file)
                    audio_files.append(file_path)
        
        if not audio_files:
            raise Exception("Could not download the song")
        
        # Move first file to main folder
        target_path = os.path.join(DOWNLOAD_PATH, os.path.basename(audio_files[0]))
        shutil.move(audio_files[0], target_path)
        return target_path
    
    except TrackPreviewUnavailableError as e:
        logging.error(f"Preview unavailable error: {str(e)}")
        raise  # Re-raise specific exception to be handled in collection_processor
    except requests.exceptions.ConnectionError:
        logging.error("Connection error during download", exc_info=True)
        raise Exception("Connection issues. Try again later")
    except requests.exceptions.Timeout:
        logging.error("Timeout during download", exc_info=True)
        raise Exception("Download is taking too long. Try again later")
    except FileNotFoundError:
        logging.error("File not found during processing", exc_info=True)
        raise Exception("This song is not currently available")
    except Exception as e:
        logging.error(f"Error during download: {str(e)}", exc_info=True)
        raise
    
    finally:
        # Clean temporary directory regardless of result
        try:
            if os.path.exists(temp_dir):
                logging.info(f"Cleaning temporary directory: {temp_dir}")
                shutil.rmtree(temp_dir, ignore_errors=True)
        except Exception as cleanup_error:
            logging.error(f"Error cleaning temporary directory: {str(cleanup_error)}")


async def enqueue_download(
    user_id: int, 
    process_func: Callable[..., Awaitable[Any]], 
    *args: Any, 
    **kwargs: Any
) -> bool:
    """
    Queues a download task in user's queue for async processing.
    
    This method is crucial to allow bot to respond to other users while
    processing long downloads. Avoids blocking the main event loop.
    
    Args:
        user_id: Telegram user ID
        process_func: Function to execute (process_track or process_collection)
        *args, **kwargs: Arguments for the processing function
            progress_message: Pre-existing progress message (optional)
        
    Returns:
        bool: True if queued successfully, False on error
    """
    # Import here to avoid circular imports
    from src.core.services import UserSession
    from src.core.services.queue_service import QueueManager
    
    try:
        # Get user session for statistics
        session = UserSession.get_session(user_id)
        session.update_activity()
        
        # Check if user has too many active downloads
        if session.active_downloads >= MAX_CONCURRENT_DOWNLOADS_PER_USER:
            logging.warning(f"User {user_id} has reached concurrent downloads limit")
            
            # If there's an existing progress message, update it
            if 'progress_message' in kwargs and kwargs['progress_message']:
                await kwargs['progress_message'].complete(
                    success=False,
                    error_message=f"You have reached the limit of {MAX_CONCURRENT_DOWNLOADS_PER_USER} simultaneous downloads. Wait for current ones to finish."
                )
            return False
        
        # Check monthly limit for normal users
        if session.role == "normal":
            # Check if month changed and reset counter if necessary
            session._check_monthly_limit_reset()
            
            # Get monthly info
            monthly_stats = session.get_monthly_downloads_left()
            remaining = monthly_stats['remaining']
            
            # Reject download if monthly limit reached
            if remaining <= 0:
                logging.warning(f"User {user_id} has reached monthly download limit ({monthly_stats['limit']})")
                
                # If there's an existing progress message, update it
                if 'progress_message' in kwargs and kwargs['progress_message']:
                    await kwargs['progress_message'].complete(
                        success=False,
                        error_message=f"⛔ You have reached the limit of {monthly_stats['limit']} monthly downloads.\n"
                        f"Consider donating to support the service and get additional benefits."
                    )
                # Otherwise, use old message method
                elif 'update' in kwargs and hasattr(kwargs['update'], 'message'):
                    await kwargs['update'].message.reply_text(
                        f"⛔ You have reached the limit of {monthly_stats['limit']} monthly downloads.\n"
                        f"Consider donating to support the service and get additional benefits."
                    )
                return False
        
        # Increment active_downloads here - for collections, this will count as only ONE download
        # regardless of how many tracks are in the collection
        session.active_downloads += 1
        session.mark_as_changed()
        
        # Get queue manager
        queue_manager = QueueManager.get_instance()
        
        # If there's a progress message, update it to indicate it's queued
        if 'progress_message' in kwargs and kwargs['progress_message']:
            content_type = kwargs.get('content_type', 'collection')
            await kwargs['progress_message'].update(
                "waiting", 
                content_type=content_type,
                queue_info="Your request is queued and will be processed shortly."
            )
        
        # Add task to user's queue through queue manager
        task = await queue_manager.enqueue_user_task(
            user_id=user_id,
            task_func=process_func,
            queue_type="downloads",
            **kwargs
        )
        
        if task:
            logging.info(f"Task queued for user {user_id}, active downloads: {session.active_downloads}")
            return True
        else:
            # If task couldn't be queued, decrement the counter we just incremented
            session.active_downloads = max(0, session.active_downloads - 1)
            session.mark_as_changed()
            
            logging.error(f"Could not queue task for user {user_id}")
            # If there's a progress message, update it to indicate error
            if 'progress_message' in kwargs and kwargs['progress_message']:
                await kwargs['progress_message'].complete(
                    success=False,
                    error_message="Error adding request to queue. Try again."
                )
            return False
        
    except Exception as e:
        # If there was any exception, make sure we decrement the counter if we incremented it
        try:
            session.active_downloads = max(0, session.active_downloads - 1)
            session.mark_as_changed()
        except Exception:
            pass
            
        logging.error(f"Error adding download to queue for user {user_id}: {str(e)}", exc_info=True)
        # If there's a progress message, update it to indicate error
        try:
            if 'progress_message' in kwargs and kwargs['progress_message']:
                await kwargs['progress_message'].complete(
                    success=False,
                    error_message="Error processing request. Try again."
                )
        except Exception:
            pass  # Ignore errors when updating error message
        return False


async def get_user_stats(user_id: int) -> Dict[str, Any]:
    """
    Gets download statistics for a specific user.
    
    Args:
        user_id: Telegram user ID
        
    Returns:
        Dictionary with user statistics including:
        - active_downloads: Number of downloads currently in progress
        - total_downloads: Total number of downloads made
        - last_activity: Timestamp of user's last activity
        - queue_stats: User's download queue statistics
    """
    # Import here to avoid circular imports
    from src.core.services import UserSession
    from src.core.services.queue_service import QueueManager
    
    # Get basic session statistics
    session = UserSession.get_session(user_id)
    stats = {
        'active_downloads': session.active_downloads,
        'total_downloads': session.total_downloads,
        'last_activity': session.last_activity
    }
    
    # Add queue statistics if available
    try:
        queue_manager = QueueManager.get_instance()
        user_queue = queue_manager.get_user_queue(user_id, "downloads")
        stats['queue_stats'] = user_queue.get_stats()
    except Exception as e:
        logging.error(f"Error getting queue stats for user {user_id}: {str(e)}")
        stats['queue_stats'] = {"error": "Could not get queue statistics"}
    
    return stats
